### PR TITLE
feature: add a component to support 12-hour clocks

### LINKED ISSUE #1: feat: Add support for 12-hours with AM/PM toggle

### PR DESCRIPTION
**Pull request by agreen254**
Introduces a new component that supports 12-hour clocks. As I expanded on the already-present skeleton for this feature, it will need the shadcn Select component to work. 

It will properly loop between 1 and 12, supports right-left arrow navigation, and will automatically update the time whenever the user switches between AM and PM.

The time is stored internally in the 24-hour format, but presented to the user in the 12-hour format.

https://github.com/openstatusHQ/time-picker/assets/101513222/0967cabd-3126-4280-b77a-17e5850b6e1d

### CODE REVIEW

**Comment by agreen254** [comment]
Updated to persist time in the datetime picker when user chooses a new day instead of resetting back to 00:00. This was causing an issue where the date could be stored internally as AM but user would read period select as PM.

**Comment by mxkaske** [comment]
Amazing @agreen254! 

The deployment fails because of _Component definition is missing display name  react/display-name_ in the `period-select.tsx` component.

If I find time, I will fix it and merge your pr! Thanks for the work.

**Comment by agreen254** [comment]
Thank you @mxkaske! Glad I could contribute!

**Comment by guppy57** [comment]
Will this be merged in soon?

**Comment by agreen254** [comment]
@mxkaske fixed the deployment issue!

**Comment by mxkaske** [comment]
Thanks @agreen254! 🔥

**Pull request merged**
